### ISSUE TITLE
Only exporting A & B

### ISSUE THREAD

**Issue by Braddeputy** [johanmattssonm/birdfont#129]
I'm attempting to export a font that I've been working on for a little while, and I when I export it as a .ttf, it only exports glyphs A and B.  What do I need to do?

**Comment by johanmattssonm** [comment]
![Screen Shot 2022-03-22 at 23 13 43](https://user-images.githubusercontent.com/350392/159585367-20b3f61a-c870-49ab-b777-d3c5668e2253.png)

It looks like Font Book on Mac sometimes just displays two letters when you view your font in progress. This can be fixed by adding both uppercase and lower case letters (A-Z & a-z).
