### ISSUE TITLE
/usr/lib64

### ISSUE THREAD

**Issue by jaboja** [johanmattssonm/birdfont#19]
Both xmlbird and birdfont install its libraries in non-standard location /usr/lib64 (it may be standard on some machines but neither configure or install.py script checks it; e.g. in my case it is /usr/lib/x86_64-linux-gnu instead). Nevertheless neither birdfonts' configure or install.py bothers to set PKG_CONFIG_PATH accordingly during install. Also installed binaries yield error of missing binaries (I assume they just look for them in system default /usr/lib instead of location the install.py script really installed them in).

I think installation scripts should either install libraries in system default library directory (and not some fixed one which is accidentally default for authors' distribution of Linux) or install them where they want and set library paths accordingly when trying to access them.

Maybe switching from Python to standard Makefile would be a solution.

**Comment by johanmattssonm** [comment]
I will keep the build system but I might try to fix the build errors. I don't understand why a build system should fiddle with PKG_CONFIG_PATH, it is up to the distribution to do this. Which distro are you using? All the big ones should work fine.
Cheers

**Comment by vapier** [comment]
seems like the libdir option already goes out of its way to try and probe a default location, including on deb based systems that do multiarch.  personally i'd just have it default to `/lib` all the time and make the person doing the building pick the right location since there's so much variety out there ... this is how autotools and other build systems work.

**Comment by hThoreau** [comment]
I believe I ran into a problem related to this. Although, being only a novice user to Debian Jessie, and Linux in general, I could only guess from the similarity of the case presented by the OP. After downloading executing the instructions from xmlbird's README file, I believe that I've successfully performed its correct installation, as displayed below:
```
chomsky@user:/home/thoreau/xmlbird$ sudo ./configure
Checking for valac version >= 0.16.0
Found Vala 0.26.1

chomsky@user:/home/thoreau/xmlbird$ sudo doit
.  mkdir build/libxmlbird
-- valac libxmlbird
-- compile build/libxmlbird/Attribute.c
-- compile build/libxmlbird/XmlTree.c
-- compile build/libxmlbird/XmlString.c
-- compile build/libxmlbird/XmlData.c
-- compile build/libxmlbird/Tag.c
-- compile build/libxmlbird/Attributes.c
-- compile build/libxmlbird/XmlElement.c
-- compile build/libxmlbird/Xml.c
-- compile build/libxmlbird/Elements.c
-- libxmlbird
.  libxmlbird_pkgconfig
chomsky@user:/home/thoreau/xmlbird$ sudo ./install.py
install: /usr/lib64/libxmlbird.so.1
install link: /usr/lib64/ libxmlbird.so
install: /usr/include/xmlbird.h
install: /usr/share/vala/vapi/xmlbird.vapi
install: /usr/lib64/pkgconfig/xmlbird.pc
```
Yet, running Birdfont's installation afterwards, as described by its own README file, yields the following result:
```
chomsky@user:/home/thoreau/Installers/birdfont-2.18.3$ sudo ./configure
Checking for valac version >= 0.16.0
Found Vala 0.26.1

Looking for library: cairo		
Looking for library: gdk-pixbuf-2.0		
Looking for library: gio-2.0		
Looking for library: glib-2.0		
Looking for library: gtk+-3.0		
Looking for library: webkit2gtk-4.0		
Looking for library: libsoup-2.4		
Looking for library: libnotify		
Looking for library: sqlite3		
Looking for library: xmlbird		
Can not find xmlbird
```
Would this be a matter of simply moving files around, or altering the `configure` file in order to `./configure` being able to find these dependencies?

**Comment by vapier** [comment]
Debian has non-standard paths for its files.  you'll probably need to adjust the flags you passed to xmlbird's configure so it goes into the right place.

you can test easily by doing something like:
`pkg-config --debug --libs xmlbird`

if that fails, try comparing it to the others like:
`pkg-config --debug --libs sqlite3`

**Comment by hThoreau** [comment]
@vapier How odd, it seems even Debian is having difficulties finding xmlbird!
```
thoreau@user:~$ pkg-config --libs xmlbird
Package xmlbird was not found in the pkg-config search path.
Perhaps you should add the directory containing `xmlbird.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xmlbird' found
```
While the command ` pkg-config --debug --libs sqlite3` yields an [extensive response](https://gist.github.com/hThoreau/ea2798a0c8b89145df19d47b13faa65b).

I'm not familiar with the concept of adjusting flags, how does that work? And gow would I go about doing that?

**Comment by finnoleary** [comment]
Hi, this is still a problem. I compiled it on Alpine linux, and birdfont installed it's libraries to `/usr/lib64` rather than the correct `/usr/lib` (It created the `/usr/lib64` directory in the process). Unfortunately the `configure` script lacks the option to set the location of `/usr/lib`, as `xmlbird`'s `configure` script has, so this necessitates manual work after installation.

**Comment by johanmattssonm** [comment]
The install.py script has a libdir option.
